### ISSUE TITLE
Add benchmark app.

### ISSUE THREAD

**Issue by artem-zinnatullin** [lyft/domic#10]
It should do same stuff differently so we could profile it (systrace, etc) and compare implementations, right now I just modify sample app and profile that.

Right now I'm thinking about at least 4 options:

- Render changes directly on main thread
- Render changes that were computed off main thread and then posted to main thread
- Render changes that were computed on main thread with Domic 
- Render changes that were computed off main thread with Domic

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
