### ISSUE TITLE
State sync between Domic and Android Framework.

### ISSUE THREAD

**Issue by artem-zinnatullin** [lyft/domic#15]
This is a tracking issue for discussions of the problem.

#### Problem

Android Framework is mutable (duh). Mostly it's fine, however some View/Widget properties can be updated by Framework/user, for example `TextView/EditText.text` or `CompoundButton.checked`.

#### Problem Example with `CheckBox`:

1. Developer sets `checked` to `false` via Domic
1. User of device clicks on it and effectively sets `checked` to `true`
1. Developer sets `checked` to `false` via Domic again

If Domic doesn't track state changed by user of the device (read as Android Framework), it will just dismiss the update because it compares it with internal in-memory state.

#### Solution

Current solution is to observe state of such properties and update internal in-memory state thus keeping Domic in sync with Android Framework.

Was discussed with lead of Android UI Framework [Adam Powell](https://twitter.com/adamwp)

**Comment by artem-zinnatullin** [comment]
There is an open question: "When do we need to start observing a property"

We can do it only after first call to `Change.property()` 
or we can do it right away when Android View/Widget is bound to Domic

Opinions are welcome!

**Comment by sockeqwe** [comment]
I don't fully understand the problem. Can you give a better example or explain the checkbox example even more?

Is this related to running into a loop because you don't know whether or not the checkbox has been changed by the user "manually" or by the developer in code?

Example (Pseudo Code, I'm not fluent with domic API): 
```
val checkboxChanges : Observable<Boolean> = checkbox
    .observe
    .checkChanges  // true or false what the current value of the checkbox is
   
  checkbox.
    .change
    .checked( checkboxChanges.map { !it } ) // you run in an endless loop because applying checkbox changes emit into checkboxChanges observable again ... 
```

**Comment by dimsuz** [comment]
@artem-zinnatullin FYI another example of such "framework set state" I have ran into is `SwipeRefreshLayout`: when user pulls it down it is immediately set to `isRefreshing = true` and outer state needs to be manually updated just as you describe for `Checkbox`

**Comment by artem-zinnatullin** [comment]
@sockeqwe sure

Problem this issue is about is state inconsistency between Android Framework and Domic that can occur if some property change to the View/Widget is triggered by Framework (ie by user of device).

If Domic won't observe state of such properties — Domic's memory state can get out of sync with Framework. Combining this with diffing (read as `distinctUntilChanged`), that can lead to pretty bad bugs like not updating the real DOM with some change because change is considered to be unnecessary even though real DOM state is different.

Example with CheckBox tries to showcase such problem when memory model states that CheckBox is already unchecked thus it dismisses the update while actual state is changed by Framework (user of device) to checked.


The loop you're talking about it is another problem that can appear because of how we solve the problem described in this issue, but so far it doesn't seem to be an issue :)

**Comment by artem-zinnatullin** [comment]
@dimsuz nice, we might want to collect all such properties in this or separate issues 👍

**Comment by artem-zinnatullin** [comment]
Updated PR with observing state of such properties right away at binding time. 

Main reason to do so is proper support for #4 - an API for dumping state out of the Domic, we can however read values off real DOM at dump time but that doesn't seem right
