### ISSUE TITLE
API to capture and apply captured state. 

### ISSUE THREAD

**Issue by artem-zinnatullin** [lyft/domic#4]
Since we pipe all changes through our model, we can expose API that can let user capture and apply captured state.

That can be helpful for state save/restore, reproducing UI from bug reports, etc.

**Comment by artem-zinnatullin** [comment]
To keep this thing efficient, we don't want to observe all properties and only capture the state of those that are programmatically changed (including some properties like `CheckBox.checked` that can be changed by user interaction).

The state object will be produced on demand, so we're not re-allocating on every property update. Properties that were not changed programmatically or by user will be `null` which is type-safe thanks to Kotlin.

Most of the bits are actually already there for this, we have an `AtomicReferenceArray` in every component that tracks state of properties, so we'll just need to convert it to type-safe data class object on request.

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
